name: Profile Automation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 1. Snake Animation
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark

      # 2. Download Streak Stats (Cache)
      - name: Download Streak Stats
        run: |
          curl -o assets/streak_stats.svg "https://streak-stats.demolab.com?user=${{ github.repository_owner }}&theme=tokyonight&hide_border=true&card_width=500&hide_current_streak=true&hide_longest_streak=true"

      # 3. Commit
      - name: Commit Assets
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ðŸ¤– Update profile assets"
          file_pattern: assets/*
